apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testenvs.example.org
spec:
  scope: Namespaced
  group: example.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Type
          type: string
          priority: 0
          jsonPath: .spec.type
          description: The type of the resource
        - name: Type
          type: string
          priority: 0
          jsonPath: .spec.hostUser
          description: Username for domain
        - name: Type
          type: string
          priority: 0
          jsonPath: .spec.namespace
          description: Created namespace

  names:
    kind: Testenv
    plural: testenvs
    singular: testenv
    shortNames:
      - te